--[[
  Atomically replay a DLQ job back to its source queue.

  Reads the DLQ job hash, creates a new job in the source queue's waiting list,
  removes the DLQ job, and emits events on both queues.

  NOTE (Redis Cluster): All keys must hash to the same slot.

  Input:
    KEYS[1]  DLQ job hash key              ({prefix}:{dlqQueue}:{dlqJobId})
    KEYS[2]  DLQ waiting list key          ({prefix}:{dlqQueue}:wait)
    KEYS[3]  source waiting list key       ({prefix}:{sourceQueue}:wait)
    KEYS[4]  source job hash key           ({prefix}:{sourceQueue}:{newJobId})

    ARGV[1]  dlqJobId
    ARGV[2]  newJobId (generated by caller)
    ARGV[3]  timestamp (ms epoch)

  Output:
    newJobId on success
    -1 DLQ job not found
    -2 Missing _dlqMeta (not a valid DLQ job)

  Events:
    waiting (on source events stream)
    removed (on DLQ events stream)
]]

local rcall = redis.call

--- @include "includes/removeJobKeys"
--- @include "includes/trimEvents"

-- TODO (features pass): implement atomic replay logic
-- Placeholder: return error code until implemented
return -1
